### ISSUE TITLE
Observers should support `on:`, e.g. `after_commit on: :create`

### ISSUE THREAD

**Issue by paulkoegel** [rails/rails-observers#18]
cf. http://stackoverflow.com/questions/7238699/rails-3-how-to-identify-after-commit-action-create-update-destroy

**Comment by Vorob-Astronaut** [comment]
@rafaelfranca It could be helpful

**Comment by heaven** [comment]
Would be great if observers support `after_create_commit`, `after_update_commit`, and `after_destroy_commit`.

**Comment by salf** [comment]
Next code works well in my application:
```
def after_commit(post)
  if action?(post, [:create, :update])
    ...
  end
end

def action?(object, actions = [])
  object.send(:transaction_include_any_action?, actions)
end
```

rails 4.2.8
