### ISSUE TITLE
`config.active_record.observers` syntax broken in Rails 5?

### ISSUE THREAD

**Issue by cannikin** [rails/rails-observers#45]
Trying to add an observer with the standard `config.active_record.observers = [:user_observer]` syntax in application.rb. But nothing ever triggers.

I was able to get them to trigger by adding an initializer with this syntax instead:

```
ActiveRecord::Base.add_observer UserObserver.instance
```

Any Rails members know of changes in Rails 5 that would have broken that config syntax?

**Comment by aghos7** [comment]
I ran into the same issue using ```config.active_record.observers = [:user_observer]```
I was able to get it to work by a similar method, but I added it in an initializer like this:
```
# config/initializers/observers.rb
User.add_observer UserObserver.instance
```

**Comment by bodrovis** [comment]
Same here, the suggested fix works great.

**Comment by ZempTime** [comment]
I'm getting this same behavior with a twist: it runs in development, but not in production.

I gotta go out of town for the weekend, but when I get back I'll try to replicate it

**Comment by ZempTime** [comment]
I just noticed, this is just waiting on: https://github.com/rails/rails-observers/pull/41

**Comment by aviav** [comment]
Maybe calling `instance` is already enough in general. In my case it fixed the failing specs. So in the example above we would add an initializer with just
```
UserObserver.instance
```

**Comment by hegwin** [comment]
It's May 15th, 2017. I just encountered this issue. I notice there are some commits, but it seems that the PR hasn't been merged?

**Comment by hegwin** [comment]
In addition, I tried to add an initializer with:

```ruby
ActiveRecord::Base.add_observer UserObserver.instance
```

And my CI failed when loading the schema, because I call some methods like `exp_changed?` (ActiveModel::Dirty) in my user observer.

```
rake aborted!
NoMethodError: undefined method `exp_changed?' for #<ActiveRecord::InternalMetadata:0x000000064a8f70>
Did you mean?  key_changed?
/home/ubuntu/change-backend/vendor/bundle/ruby/2.3.0/gems/activemodel-5.0.0/lib/active_model/attribute_methods.rb:433:in `method_missing'
/home/ubuntu/change-backend/app/models/user_observer.rb:3:in `after_save'
/home/ubuntu/change-backend/vendor/bundle/ruby/2.3.0/bundler/gems/rails-observers-206cb17bc14f/lib/rails/observers/active_model/observing.rb:352:in `update'
/home/ubuntu/change-backend/vendor/bundle/ruby/2.3.0/bundler/gems/rails-observers-206cb17bc14f/lib/rails/observers/activerecord/observer.rb:118:in `block (2 levels) in define_callbacks'
```

My solution is to add observers directly to my model:
```ruby
User.add_observer UserObserver.instance
```
Then CI passed.

**Comment by rogerkk** [comment]
@hegwin Have you seen https://github.com/rails/rails-observers/pull/41, seems like a fix for the loading issue might be close.

**Comment by dugsmith** [comment]
I just experienced this issue with Rails 4.2.8. The fix was to add `MyObserver.instance` to an initializer. With that, tests pass.

**Comment by kaspth** [comment]
Could be related to #65. Try 0.1.5!

**Comment by dugsmith** [comment]
@kaspth Yes, thank you! 0.1.5 worked great.

**Comment by adamzolotarev** [comment]
Just encountered this issue with Rails 5 upgrade and already using 0.1.5. Also fixed by calling `MyObserver.instance` in the initializer.

**Comment by Gaurav3khede** [comment]
> Just encountered this issue with Rails 5 upgrade and already using 0.1.5. Also fixed by calling `MyObserver.instance` in the initializer.

Hi,
 Sorry, I am new to rails.
 Can you please explain this a bit more? Thanks.
 Do I need to create new `initializer` under `config/initializers` ? 
Regards,
Gaurav
