### ISSUE TITLE
The Rails app gets loading during migrations with registered observers.

### ISSUE THREAD

**Issue by kellyjosephprice** [rails/rails-observers#51]
### Steps to reproduce

I've created an example app [here](https://github.com/kellyjosephprice/example_app/commit/61d7ef01192b4301c83b43b6178916f1bb8bfafa). It has a `User` model and a pending migration. The user model will `raise` when loaded. 

So the following happens:

```
% rake db:migrate
rake aborted!
application loaded too early
/Users/kelly/git/example_app/app/models/user.rb:2:in `<class:User>'
...
```

### Expected behavior

It was my understanding that an app shouldn't be loaded during migrations, and the app our company uses has many cases where it makes that assumption. 

### System configuration

```
% rails --version
Rails 4.2.1
% ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

**Comment by rafaelfranca** [comment]
Could you check the master branch? Also, the app is always loaded during the migrations, the entire environment is loaded, with and without observer, so I'm not sure what is failing here. You example application doesn't have anything that is failing and there is no model there.

**Comment by kellyjosephprice** [comment]
Oops, sorry about that. Here's a commit as I meant to post: https://github.com/kellyjosephprice/example_app/commit/1bcfa6108d70dc385958300385b963eae79994f5

If you're saying that the app is intended to be loaded during migrations, then my base assumptions are wrong.

**Comment by rafaelfranca** [comment]
in fact it is loaded before migrations in the `rake environment` task. In production environment the entire app folder is eager loaded, so models are loaded before migrations too. But the fact that models were being loaded by rails-observers too early should be fixed in the master branch. Have you checked it?

**Comment by kellyjosephprice** [comment]
Yes, thank you. It works fine on the master branch: https://github.com/kellyjosephprice/example_app/commit/4783adadb4a863b763c966f488df3f464cc5fc4a
