### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by dblock** [rails/rails-observers#55]
Can we please release a version of this gem? I had to use HEAD for https://github.com/mongoid/mongoid-slug/pull/234.

**Comment by rafaelfranca** [comment]
It will be released when it is done. Until there you can keep using HEAD

**Comment by dblock** [comment]
Thanks @rafaelfranca. Since I am sure this is a common request and downstream libraries would like to know when there's a release, maybe keep this issue open? No need to reply.

**Comment by rafaelfranca** [comment]
Make sense

**Comment by westonganger** [comment]
Its been 7 months since the last commit. 

If its been that long and quite a few other people are using it then it surely deserves a new version. Then you can release another version later.

**Comment by lpil** [comment]
It would be great to get a new release rather than rely on HEAD for the latest version :)

**Comment by thomasfedb** [comment]
Am also interested when this might get a refresh. Trying to use https://github.com/collectiveidea/audited with Rails 5, which currently requires using the git version of rails-observers.

**Comment by rafaelfranca** [comment]
To have a new release we need to fix https://github.com/rails/rails-observers/pull/41 first

**Comment by thomasfedb** [comment]
Ended up finding a way to avoid using rails-observers.

**Comment by kaspth** [comment]
#41 was fixed in #65 and there's a new 0.1.5 out.
